language: node_js
node_js:
  - "12"
addons:
  apt:
    packages:
      - g++-4.8
      - nasm
    sources:
      - ubuntu-toolchain-r-test
env:
  CXX=g++-4.8
branches:
  only:
    - master
before_script:
  - "apk add make zlib autoconf automake libtool dpkg pkgconfig libpng libpng-dev g++"
  - "yarn global add firebase-tools"
  - "yarn global add gatsby"
script:
  - "gatsby build --prefix-paths"
after_success:
  - "firebase deploy --token=${FIREBASE_API_TOKEN}"
